version: '3.8'

services:
  geth:
    image: ethereum/client-go:stable
    volumes:
      - ./geth-data:/data
    ports:
      - "8545:8545"
      - "8546:8546"
    command: >
      --dev
      --datadir=/data
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.corsdomain="*"
      --http.api="eth,net,web3,personal,miner,txpool"
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins="*"
      --ws.api="eth,net,web3,personal,miner,txpool"
      --mine
      --allow-insecure-unlock
    restart: unless-stopped