apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erc20-geth.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "erc20-geth.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erc20-geth.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erc20-geth.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: geth
        image: "{{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}"
        imagePullPolicy: {{ .Values.geth.image.pullPolicy }}
        command: ["/bin/sh", "/scripts/entrypoint.sh"]
        ports:
        - containerPort: {{ .Values.geth.service.httpPort }}
          name: http-rpc
        - containerPort: {{ .Values.geth.service.wsPort }}
          name: ws-rpc
        env:
        - name: GETH_NETWORK
          value: "{{ .Values.geth.network }}"
        - name: GETH_DATA_DIR
          value: "/data/geth"
        - name: GETH_RPC_PORT
          value: "{{ .Values.geth.service.httpPort }}"
        - name: GETH_WS_PORT
          value: "{{ .Values.geth.service.wsPort }}"
        volumeMounts:
        - name: geth-storage
          mountPath: /data/geth
        - name: scripts-volume
          mountPath: /scripts
        {{- with .Values.geth.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: geth-storage
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "erc20-geth.fullname" . }}-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: scripts-volume
        configMap:
          name: {{ include "erc20-geth.fullname" . }}-scripts
          defaultMode: 0755 